newsItem:
  displayName: News items
  fields:
    title:
      type: string
      displayName: Title
      showInSummary: true
      isRequired: true
    image:
      type: string
      displayName: Image
      displayExtra: 'Recommended aspect ratio: 20:9 (e.g. 800x360 px). Please, do not use images that contain text.'
      showInSummary: true
      dontTranslate: true
      isRequired: true
      isUploadedFile: true
    date:
      type: string
      displayName: Publication date
      displayExtra: 'Format: yyyy/mm/dd'
      showInSummary: true
      isRequired: true
      dontTranslate: true
    isHidden:
      type: boolean
      displayName: Hidden
      showInSummary: true
    standfirst:
      type: string
      displayName: Standfirst
      isRequired: true
    body:
      type: markdown
      displayName: News item body
      displayExtra: You can use Image, Screenshot, Button and YoutubeEmbed custom blocks
      height: 300

page:
  displayName: Pages
  fields:
    title:
      type: markdown
      displayName: Page title
      displayExtra: 'Example: Meet our **team**'
      showInSummary: true
      isRequired: true
    layout:
      type: markdown
      displayName: Layout
      height: 300
      allowCustomBlocks: true
      isRequired: true
    contents:
      type: markdown
      displayName: Contents
      height: 300
      allowCustomBlocks: true
      isRequired: true
    unfurlTitle:
      type: string
      displayName: Unfurl title
      displayExtra: 'Seen when sharing on Twitter, Facebook, Slack, WhatsApp…'
    unfurlDescription:
      type: string
      displayName: Unfurl description
    unfurlImage:
      type: string
      displayName: Unfurl image
      dontTranslate: true
      isUploadedFile: true

incident:
  displayName: Incidents
  fields:
    title:
      type: string
      displayName: Title
      displayExtra: Used as tab title, page title in search results (SEO) and when sharing page in social networks
      showInSummary: true
      isRequired: true
    severity:
      type: select
      displayName: Severity
      displayExtra: Minor incidents can affect some users in one service. Major incidents affect all users in one or more services.
      showInSummary: true
      isRequired: true
      choicesFixed:
        - Minor
        - Major
    startDate:
      type: string
      displayName: Start date
      displayExtra: 'Assumes France local time. Format: yyyy/mm/dd hh:mm'
      showInSummary: true
      isRequired: true
      dontTranslate: true
    endDate:
      type: string
      displayName: End date
      displayExtra: 'Assumes France local time. Format: yyyy/mm/dd hh:mm'
      showInSummary: true
      dontTranslate: true
    affectedServices:
      type: string
      isMultiple: true
      displayName: Affected services
      isRequired: true
      choicesFixed:
        - All services
        - Web portal
        - 'Data Discovery Platform (online catalogue; viewer and subsetter)'
        - Single-Sign On
        - Harmonised Data Access
        - 'Other APIs (WMS; CSW)'
        - Specific datasets
        - Jupyter Notebooks
        - Compute Platform (VM management)
        - 'Compute Platform (VM instantiation; start/stop…)'
        - Tenant management
        - WEkEO Drive
    displayInHomepage:
      type: boolean
      displayName: Display in homepage
    homepageAnnouncementStartDate:
      type: string
      displayName: Homepage announcement start date
      displayExtra: 'Assumes France local time. Format: yyyy/mm/dd hh:mm'
      showInSummary: true
      dontTranslate: true
    contents:
      type: markdown
      displayName: Contents
      isRequired: true
      height: 300

about:
  displayName: About page
  singleton: true
  fields:
    title:
      type: string
      displayName: Title
      displayExtra: Used as tab title, page title in search results (SEO) and when sharing page in social networks
      showInSummary: true
      isRequired: true
    description:
      type: string
      displayName: Description
      displayExtra: Used as page description in search results (SEO) and when sharing page in social networks
      showInSummary: true
      isRequired: true
    heroText:
      type: string
      displayName: Hero text
      isRequired: true
    contents:
      type: markdown
      displayName: Page contents
      isRequired: true
      height: 300
    entityLinkLabel:
      type: string
      displayName: Entity link label
      isRequired: true

aboutEntities:
  displayName: About page entities
  allowManualSorting: true
  fields:
    logo:
      type: string
      displayName: Logo
      displayExtra: In grayscale, displayed over a dark blue background
      showInSummary: false
      isRequired: true
      dontTranslate: true
      isUploadedFile: true
    description:
      type: markdown
      displayName: Description
      showInSummary: false
      isRequired: true
      height: 300
    url:
      type: string
      displayName: URL
      showInSummary: true
      isRequired: true
      dontTranslate: true

support:
  displayName: Support page
  singleton: true
  fields:
    title:
      type: string
      displayName: Title
      displayExtra: Used as tab title, page title in search results (SEO) and when sharing page in social networks
      showInSummary: true
      isRequired: true
    description:
      type: string
      displayName: Description
      displayExtra: Used as page description in search results (SEO) and when sharing page in social networks
      showInSummary: true
      isRequired: true
    heroText:
      type: string
      displayName: Hero text
      isRequired: true
    intro:
      type: string
      displayName: Page intro
      isRequired: true
    supportOpt:
      type: markdown
      displayName: Support options
      displayExtra: Please list 4 support options of your product and provide a small description for each. Use only 4 SupportCard custom blocks.
      isRequired: true
      height: 300
    formTitle:
      type: string
      displayName: Form title
      isRequired: true

datasetOutage:
  displayName: Dataset outages
  fields:
    datasetId:
      type: string
      displayName: Dataset ID prefix
      displayExtra: All datasets IDs starting with this text will be matched by this outage
      isRequired: true
      dontTranslate: true
      showInSummary: true
    startTime:
      type: string
      displayName: Start time
      displayExtra: 'Assumes France local time. Format: yyyy/mm/dd hh:mm'
      isRequired: true
      dontTranslate: true
      showInSummary: true
    stopTime:
      type: string
      displayName: Stop time
      displayExtra: 'Assumes France local time. Format: yyyy/mm/dd hh:mm. Leave blank for unknown stop time.'
      dontTranslate: true
      showInSummary: true
    reason:
      type: string
      displayName: Outage reason
      showInSummary: true

pressKitSection:
  displayName: Press corner section
  singleton: true
  fields:
    aboutWekeo:
      type: markdown
      displayName: About WEkEO
      isRequired: true
      showInSummary: true
      height: 300
    pressContactInfo:
      type: markdown
      displayName: Press contact information
      isRequired: true
      showInSummary: true
      height: 100
    pressKitFile:
      type: string
      displayName: Press kit file
      displayExtra: Lino to download it will appear on Press Corner sidebar
      isRequired: true
      isUploadedFile: true
      dontTranslate: true
    mediaContents:
      type: markdown
      displayName: Media page contents
      isRequired: true
      showInSummary: true
      height: 300
    brandAssetsContents:
      type: markdown
      displayName: Brand assets page contents
      isRequired: true
      showInSummary: true
      height: 300

pressRelease:
  displayName: Press releases
  fields:
    title:
      type: string
      displayName: Title
      showInSummary: true
      isRequired: true
    image:
      type: string
      displayName: Image
      isRequired: true
      isUploadedFile: true
      dontTranslate: true
    location:
      type: string
      displayName: Location
      showInSummary: true
      isRequired: true
    date:
      type: date
      displayName: Date
      showInSummary: true
      isRequired: true
      dontTranslate: true
    standfirst:
      type: string
      displayName: Standfirst
      isRequired: true
    body:
      type: markdown
      displayName: Body
      height: 300
      isRequired: true

clipping:
  displayName: Clipping (WEkEO in the news)
  fields:
    title:
      type: string
      displayName: Title
      showInSummary: true
      isRequired: true
    link:
      type: string
      displayName: Link
      showInSummary: true
      isRequired: true
      dontTranslate: true
    date:
      type: date
      displayName: Date
      showInSummary: true
      isRequired: true
      dontTranslate: true
    mediaName:
      type: string
      displayName: Media name
      isRequired: true
    mediaLogo:
      type: string
      displayName: Media logo
      isRequired: true
      dontTranslate: true
      isUploadedFile: true

brandAssets:
  displayName: Brand assets
  singleton: true
  fields:
    title:
      type: string
      displayName: Title
      isRequired: true
      showInSummary: true
    body:
      type: markdown
      displayName: Body
      displayExtra: You can use 'BrandAsset' custom blocks.
      isRequired: true
      showInSummary: true
      height: 400

useCase:
  displayName: Use cases
  fields:
    hidden:
      type: boolean
      displayName: Hidden
      displayExtra: Hidden use cases are not linked from the Use cases front page, but accessible by URL
      showInSummary: true
    productName:
      type: string
      displayName: Produt name
      showInSummary: true
    title:
      type: string
      displayName: Title
      displayExtra: Max. 70 characters. Choose an enticing title, focus on the key features of your product.
      showInSummary: true
    createdAt:
      type: date
      displayName: Created at
      showInSummary: true
    shortDescription:
      type: string
      displayName: Short description
      displayExtra: Synthesise this project, featuring its key aspects, in one paragraph.
      showInSummary: true
    detailedDescription:
      type: markdown
      displayName: Detailed description
      displayExtra: Please provide an overview of your product, its goals and motivations and a description of the parthership.
      height: 300
    creators:
      type: markdown
      height: 200
      displayName: Creators
      displayExtra: Use only UseCaseCreator custom blocks. At least 1, 5 at most.
    creatorsText:
      type: markdown
      height: 200
      displayName: Creators text
      displayExtra: Use this section if you would like to add a few words about the consortium or the specific people that have implemented the service.
    coverImageExternal:
      type: string
      displayName: Cover image (external source)
      dontTranslate: true
      displayExtra: This field is populated with Unsplash data (from Use case submission form)
    coverThumbnailExternal:
      type: string
      displayName: Cover thumbnail (external source)
      dontTranslate: true
      displayExtra: This field is populated with Unsplash data (from Use case submission form)
    coverImageAuthorName:
      type: string
      displayName: Cover image author name
      dontTranslate: true
      displayExtra: This field is populated with Unsplash data (from Use case submission form)
    coverImageAuthorUrl:
      type: string
      displayName: Cover image author URL
      dontTranslate: true
      displayExtra: This field is populated with Unsplash data (from Use case submission form)
    coverImage:
      type: string
      displayName: Cover image (uploaded file)
      dontTranslate: true
    coverThumbnail:
      type: string
      displayName: Cover thumbnail (uploaded file)
      dontTranslate: true
    coverImageTop:
      type: number
      displayName: Cover image position
      displayExtra: 'As a percentage. 0% snaps the image to the top, 100% to the bottom.'
    country:
      type: string
      displayName: Country
      choicesPreviousValues: true
    region:
      type: string
      displayName: Region
      choicesPreviousValues: true
    market:
      type: string
      displayName: Market
      choicesPreviousValues: true
    descriptionPrimaryImage:
      type: string
      displayName: Description image (primary)
      displayExtra: Please provide a high resolution image of the service in action or any other relevant image. Minimum width is 1500px. Horizontal images are preferred.
      isUploadedFile: true
      dontTranslate: true
    descriptionPrimaryImageLegend:
      type: string
      displayName: Description image (primary) legend
    descriptionVideoUrl:
      type: string
      displayName: Description video URL
      dontTranslate: true
    descriptionVideoFile:
      type: string
      displayName: Description video file
      isUploadedFile: true
      dontTranslate: true
    descriptionVideoFallbackImage:
      type: string
      displayName: Description video fallback image (if video not available)
      isUploadedFile: true
    descriptionVideoLegend:
      type: string
      displayName: Description video (or image fallback) legend
    keyFeatures:
      type: markdown
      height: 200
      displayName: Key Features
      displayExtra: Please list 3 features of your product and provide a small description for each. The 3 features should highlight the strongest features of your service. Use only 3 UseCaseKeyFeature custom blocks.
    benefits:
      type: markdown
      height: 200
      displayName: Benefits
      displayExtra: One short paragraph and a bullet list of benefits
    benefitsImage:
      type: string
      displayName: Benefits image
      displayExtra: Square image, avoid using screenshots. Optimal size is 1000x1000px.
      dontTranslate: true
      isUploadedFile: true
    benefitsImageExternal:
      type: string
      displayName: Benefits image (external source)
      dontTranslate: true
      displayExtra: This field is populated with Unsplash data (from Use case submission form)
    benefitsImageAuthorName:
      type: string
      displayName: Benefits image author name
      dontTranslate: true
      displayExtra: This field is populated with Unsplash data (from Use case submission form)
    benefitsImageAuthorUrl:
      type: string
      displayName: Benefits image author URL
      dontTranslate: true
      displayExtra: This field is populated with Unsplash data (from Use case submission form)
    datasetIds:
      type: string
      displayName: Datasets in use
      displayExtra: IDs of datasets, comma separated
      placeholder: EO:MO:DAT:GLOBAL_ANALYSISFORECAST_PHY_001_024
      isMultiple: true
      choicesPreviousValues: true
      dontTranslate: true
    contactInfo:
      type: markdown
      height: 200
      displayName: Contact information
      displayExtra: Entered by use case author in the use case submission form. This will not be displayed in the use case page.
    comments:
      type: markdown
      height: 200
      displayName: Comments
      displayExtra: Entered by use case author in the use case submission form. This will not be displayed in the use case page.
    draftVideos:
      type: markdown
      height: 200
      displayName: Draft videos
      displayExtra: Entered by use case author in the use case submission form. This field contains a list of uploaded video files (available in Editorial) and/or external video links. These video resources may be edited to produce a video and use it as the "Description video file" (see input field above)
