import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
    // {
    //   type: 'category',
    //   label: 'Core Concepts',
    //   items: [
    //     'core-concepts/content-types',
    //     'core-concepts/fields',
    //     'core-concepts/relationships',
    //     'core-concepts/media',
    //   ],
    // },
    // {
    //   type: 'category',
    //   label: 'API Reference',
    //   items: [
    //     'api/authentication',
    //     'api/content-api',
    //     'api/media-api',
    //     'api/webhooks',
    //   ],
    // },
    // {
    //   type: 'category',
    //   label: 'Guides',
    //   items: [
    //     'guides/content-modeling',
    //     'guides/rich-text-editor',
    //     'guides/localization',
    //     'guides/deployment',
    //   ],
    // },
    // {
    //   type: 'category',
    //   label: 'Integrations',
    //   items: [
    //     'integrations/frontend-frameworks',
    //     'integrations/nextjs',
    //     'integrations/react',
    //     'integrations/other-platforms',
    //   ],
    // },
  ],
};

export default sidebars;
